name: 'GitHub Actions Ruby Sample'
description: 'A sample GitHub Actions'
author: 'noraworld'
inputs: 
  my_variable:
    description: 'My variable'
    default: 'default_variable'
  my_secret_variable:
    description: 'My secret variable'
    default: 'default_secret'
outputs:
  changed_files:
    description: 'Get changed files'
    value: ${{ steps.get-changed-files.outputs.files }}
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
      uses: ruby/setup-ruby@v1
    # uses: ruby/setup-ruby@473e4d8fe5dd94ee328fdfca9f8c9c7afc9dae5e
      with:
        ruby-version: '3.1'
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
        
    - id: get-changed-files
      name: Get changed files
      run: echo "::set-output name=files::$(git diff --name-only --diff-filter=AMD)"
      shell: sh
      
    - name: test
      run: git diff --name-only --diff-filter=AMD
      shell: sh

    - name: Run sample app
      run: ruby app.rb
      shell: sh
      env:
        MY_VARIABLE: ${{ inputs.my_variable }}
        MY_SECRET_VARIABLE: ${{ inputs.my_secret_variable }}
        CHANGED_FILES: ${{ steps.get-changed-files.outputs.changed_files }}
