name: 'GitHub Actions Ruby Sample'
description: 'A sample GitHub Actions'
author: 'noraworld'
inputs: 
  my_variable:
    description: 'My variable'
    default: 'default_variable'
  my_secret_variable:
    description: 'My secret variable'
    default: 'default_secret'
  added_files:
    description: 'Get added files'
  modified_files:
    description: 'Get modified files'
  deleted_files:
    description: 'Get deleted files'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Ruby
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
      uses: ruby/setup-ruby@v1
    # uses: ruby/setup-ruby@473e4d8fe5dd94ee328fdfca9f8c9c7afc9dae5e
      with:
        ruby-version: '3.1'
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
        
    - id: get-added-files
      name: Get added files
      run: echo "::set-output name=files::$(git diff --name-only --diff-filter=A ${{ github.event.before }} ${{ github.sha }} | xargs)"
      shell: sh
      
    - id: get-modified-files
      name: Get modified files
      run: echo "::set-output name=files::$(git diff --name-only --diff-filter=M ${{ github.event.before }} ${{ github.sha }} | xargs)"
      shell: sh
      
    - id: get-deleted-files
      name: Get deleted files
      run: echo "::set-output name=files::$(git diff --name-only --diff-filter=D ${{ github.event.before }} ${{ github.sha }} | xargs)"
      shell: sh

    - name: Run sample app
      run: ruby app.rb
      shell: sh
      env:
        MY_VARIABLE: ${{ inputs.my_variable }}
        MY_SECRET_VARIABLE: ${{ inputs.my_secret_variable }}
        ADDED_FILES: ${{ steps.get-added-files.outputs.files }}
        MODIFIED_FILES: ${{ steps.get-modified-files.outputs.files }}
        DELETED_FILES: ${{ steps.get-deleted-files.outputs.files }}
