name: 'GitHub Actions Ruby Sample'
description: 'A sample GitHub Actions'
author: 'noraworld'
inputs: 
  dir:
    description: 'Specify a directory in which files you want to track and publish to Qiita'
    required: true
  qiita_access_token:
    description: 'Specify your Qiita access token'
    required: true
  mapping_filepath:
    description: 'Specify any file path in which you want to put the mapping file'
    required: false
    default: 'mapping.txt'
  added_files:
    description: 'Get added files'
  modified_files:
    description: 'Get modified files'
  deleted_files:
    description: 'Get deleted files'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Ruby
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
      uses: ruby/setup-ruby@v1
    # uses: ruby/setup-ruby@473e4d8fe5dd94ee328fdfca9f8c9c7afc9dae5e
      with:
        ruby-version: '3.1'
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
        
    - id: get-added-files
      name: Get added files
      run: echo "::set-output name=files::$(git diff --name-only --diff-filter=A ${{ github.event.before }} ${{ github.sha }} | xargs)"
      shell: sh
      
    - id: get-modified-files
      name: Get modified files
      run: echo "::set-output name=files::$(git diff --name-only --diff-filter=M ${{ github.event.before }} ${{ github.sha }} | xargs)"
      shell: sh
      
    - id: get-deleted-files
      name: Get deleted files
      run: echo "::set-output name=files::$(git diff --name-only --diff-filter=D ${{ github.event.before }} ${{ github.sha }} | xargs)"
      shell: sh

    - name: Run sample app
      run: ruby app.rb
      shell: sh
      env:
        DIR: ${{ inputs.dir }}
        QIITA_ACCESS_TOKEN: ${{ inputs.qiita_access_token }}
        MAPPING_FILEPATH: ${{ inputs.mapping_filepath }}
        ADDED_FILES: ${{ steps.get-added-files.outputs.files }}
        MODIFIED_FILES: ${{ steps.get-modified-files.outputs.files }}
        DELETED_FILES: ${{ steps.get-deleted-files.outputs.files }}
